environment:
  NODE_ENV: test
  matrix:
    - nodejs_version: "stable"
    - nodejs_version: "6"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set progress=false
  - npm install
test_script: npm run test:appveyor
build: off
cache: node_modules
