sudo: false
language: node_js
node_js:
  - stable
before_script:
  - npm install
  - npm test
  - npm run lint
after_success:
  - npm install codecov -g
  - npm run postcover
notifications:
  slack: about-hiroppy:rzKYJ3zRPzBaak3TeaTmPSH5
