sudo: false
language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
node_js:
  - stable
os:
  - linux
before_script:
  - npm install yarn -g
  - yarn install
  - yarn link || true
  - npm test
  - npm run lint
after_success:
  - npm install codecov -g
  - npm run postcover
notifications:
  slack: about-hiroppy:rzKYJ3zRPzBaak3TeaTmPSH5
